### ISSUE TITLE
Struggling with Directions

### ISSUE THREAD

**Issue by PakMan6** [mapsplugin/ionic-googlemaps-quickdemo-v5#5]
Hi,
I'm fairly new to native google maps (I've used Maps JavascriptAPI successfuly in the past). I followed the quickdemo-v5 example and managed to get "current device location" and "geocoder" to work but I'm unable to get directions to work as it gives me an error as below when I call the requestDirection() method. Can anyone please help me solve this problem. 

ERROR Error: Uncaught (in promise): TypeError: Cannot redefine property: waypoints
TypeError: Cannot redefine property: waypoints
    at Function.defineProperty (<anonymous>)
    at new DirectionsRenderer (DirectionsRenderer.js:55)
    at Map.addDirectionsRenderer (Map.js:1156)
    at index.js:1762
    at GoogleMap.push../node_modules/@ionic-native/google-maps/index.js.GoogleMap.addDirectionsRendererSync (index.js:1774)
    at home.page.ts:208
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:41667)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at Zone.run (zone-evergreen.js:123)
    at resolvePromise (zone-evergreen.js:798)
    at zone-evergreen.js:864
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41645)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)

I copied and used the code from the quickdemo-v5 example.. snippet below:

requestDirection() {
    DirectionsService.route({
      origin: this.origin,
      destination: this.destination,
      travelMode: TravelModeId.DRIVING
    }).then((result: DirectionsResult) => {
      console.log(JSON.stringify(result, null, 2));
      this.bounds = result.routes[0].bounds;

      console.log(this.bounds);

      if (!this.renderer) {
        this.renderer = this.map.addDirectionsRendererSync({
          directions: result,
          panel: 'guide',
          draggable: true
        });
        console.log(this.renderer);
        this.renderer.on(GoogleMapsEvent.DIRECTIONS_CHANGED).subscribe(this.onDirectionChanged.bind(this));
        console.log(this.renderer.on(GoogleMapsEvent.DIRECTIONS_CHANGED).subscribe(this.onDirectionChanged.bind(this)));
      } else {
        this.renderer.setDirections(result);
        console.log(this.renderer.setDirections(result));
      }
    });
  }

  onDirectionChanged() {
    const directions: DirectionsResult = this.renderer.getDirections();
    this.origin = directions.routes[0].legs[0].start_location;
    this.destination = directions.routes[0].legs[0].end_location;
    this.bounds = directions.routes[0].bounds;
  }

  onSplitterDragEnd() {
    this.map.animateCamera({
      target: this.bounds,
      duration: 500
    });

  }

   // Update server with user position
   updateDBPosition() {
    this.uID = this.authService.userData.uid;
    this.updateValues = {
      currentPosition: this.userPosition,
      // status: 'online',
    };
    this.userPositionService.update_userPosition(this.uID, this.updateValues);
  }

**Comment by timkovik** [comment]
Not assigned, but work: https://github.com/mapsplugin/cordova-plugin-googlemaps/pull/2821
(look at the diff)

**Comment by PakMan6** [comment]
@timkovik Thank you. I restarted the project and It's working :-) . Thanks for feedback

**Comment by sachi097** [comment]
Hi @PakMan6 

Does this fix work on production build app?
Were you able to get directions in production build app after this fix?
